-- Création de la table Game dans le schéma de production (APP)

CREATE TABLE APP.GAME (
	GAME_ID 		SMALLINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NAME 			VARCHAR(100),
	DESCRIPTION		VARCHAR(1000),
	CATEGORY		VARCHAR(20),
	EDITOR 			VARCHAR(50),
	AUTHOR 			VARCHAR(50),
	PUBLISHING_YEAR INT,
	NB_PLAYERS 		INT
);


-- Création de la table Game dans le schéma de test (TEST)

CREATE TABLE TEST.GAME (
	GAME_ID 		SMALLINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NAME 			VARCHAR(100),
	DESCRIPTION		VARCHAR(1000),
	CATEGORY		VARCHAR(20),
	EDITOR 			VARCHAR(50),
	AUTHOR 			VARCHAR(50),
	PUBLISHING_YEAR INT,
	NB_PLAYERS 		INT
);